run:
  modules-download-mode: readonly

# all available settings of specific linters
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  funlen:
    lines: 60
    statements: 40

  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/pbabbicola,gitlab.com/pbabbicola
  gocyclo:
    min-complexity: 10
  gocognit:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120
  nakedret:
    max-func-lines: 10
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
  whitespace:
    multi-if: true
    multi-func: false

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - gochecknoglobals
    - gocognit
    - godox
    - maligned
    - prealloc
    - wsl

issues:
  max-issues-per-linter: 3
